### ISSUE TITLE
implicit declaration of function ‘V4L2_FIELD_IS_INTERLACED’;  branch release/4.3/rpi_main

### ISSUE THREAD

**Issue by DrakonPL** [jc-kynesim/rpi-ffmpeg#24]
Sorry to bother you. I'm trying to compile brach (release/4.3/rpi_main) but for some reason have this error:

libavcodec/v4l2_buffers.c: In function ‘v4l2_buf_is_interlaced’:
libavcodec/v4l2_buffers.c:341:12: error: implicit declaration of function ‘V4L2_FIELD_IS_INTERLACED’; did you mean ‘V4L2_VBI_INTERLACED’? [-Werror=implicit-function-declaration]
     return V4L2_FIELD_IS_INTERLACED(buf->buf.field);
            ^~~~~~~~~~~~~~~~~~~~~~~~
            V4L2_VBI_INTERLACED

I'm using gcc version 8.3.0 (Raspbian 8.3.0-6+rpi1) on my pi4.
Have you ever had similar problem ?

**Comment by jc-kynesim** [comment]
V4L2_FIELD_IS_INTERLACED should be declared in /usr/include/linux/videodev2.h - it certainly exists for me with a standard bullseye release & apt-get build-dep ffmpeg.
