### ISSUE TITLE
Spurious (?) "Unexpected input whilst draining" warning with h264_v4l2m2m

### ISSUE THREAD

**Issue by egnor** [jc-kynesim/rpi-ffmpeg#26]
While it's relatively harmless, I see "unexpected input whilst draining" messages while completing an h.264 video using h264_v4l2m2m on the Pi:

```
% build/hello_drmprime jellyfish-3-mbps-hd-h264.mkv
No connector ID specified.  Choosing default from list:
Connector 32 (crtc 76): type 11, 1920x1080 (chosen)
Connector 40 (crtc 0): type 11, 0x0
[h264_v4l2m2m @ 0x2eb0320] level=40
[h264_v4l2m2m @ 0x2eb0320] Using device /dev/video10
[h264_v4l2m2m @ 0x2eb0320] driver 'bcm2835-codec' on card 'bcm2835-codec-decode' in mplane mode
[h264_v4l2m2m @ 0x2eb0320] requesting formats: output=H264 capture=YU12
[h264_v4l2m2m @ 0x2eb0320] Unexpected input whilst draining
[h264_v4l2m2m @ 0x2eb0320] Unexpected input whilst draining
```

(This is using the `hello_drmprime` example.) This seems to come from [this part of v4l2_m2m_dec.c](https://github.com/jc-kynesim/rpi-ffmpeg/blob/release/4.3/rpi_main/libavcodec/v4l2_m2m_dec.c#L388):

```
    if (s->draining) {
        if (!s->buf_pkt.size) {
            av_log(avctx, AV_LOG_WARNING, "Unexpected input whilst draining\n");
            av_packet_unref(&s->buf_pkt);
        }
        return NQ_DRAINING;
    }
```

I'm not an expert at ffmpeg internals, BUT... shouldn't the `if (!s->buf_pkt.size)` be `if (s->buf_pkt.size)` instead? (That is, a NON-empty packet is surprising while draining.)

**Comment by jc-kynesim** [comment]
That logic seems sound to me. Wonder why I've never seen that? Either way I think you are right.

**Comment by jc-kynesim** [comment]
Fixed - thanks
