### ISSUE TITLE
Building on 64bits

### ISSUE THREAD

**Issue by lockywolf** [jc-kynesim/rpi-ffmpeg#32]
The official configure script seems to be expecting 32bits only, and is tied to rpi userspace (mmal).

Is it possible to build  rpi-ffmpeg on a 64bit system? (Slarm64 if that matters.)

**Comment by jc-kynesim** [comment]
Try the pi-util/conf_native.sh script from dev/4.4/rpi_import_1 - that definitely works on PiOS 64 (I've just checked) and has options for mmal/no-mmal.  I probably haven't backported everything to 4.3.2.  The conf_pi* cross-compile scripts have undoubtedly rotted hard but were sort of hanging around as a hint I might want to fix them, but these days native compile is fast enough that it has not been any sort of priority.

**Comment by lockywolf** [comment]
Hm.... can't say that upstream ffmpeg plays 4k h265 smoothly.... even if recoded with a -fastdecode profile.

But the code seem to have built fine, even though the prefixes are a bit messed up. I'll close.

**Comment by jc-kynesim** [comment]
If you have h/w (stateless V4L2) H265 decode and direct drm display then its smooth, otherwise not.
