### ISSUE TITLE
h264_v4l2m2m no stream over rtsp

### ISSUE THREAD

**Issue by spookyfirehorse** [jc-kynesim/rpi-ffmpeg#41]
stream is running but by the reciver can not play in the new rpi ffmpeg

**Comment by rockypurba** [comment]
Hi spookyfirehouse,
I have a question. I am following your syntax and am using rtsp-simple-server, but somehow I can't get any video from the browser.
Here is my syntax: ffmpeg -async -1 -hwaccel:v drm -input_format yuyv422 -f v4l2 -i /dev/video1 -pix_fmt yuv420p -c:v h264_v4l2m2m -f rtsp -rtsp_transport tcp rtsp://localhost:$RTSP_PORT/$RTSP_PATH
I am not using any audio. And my hardware is a Raspberry Pi 3B with a Logitech webcam.
Any help would be appreciated.
Thanks.

**Comment by spookyfirehorse** [comment]
working
