### ISSUE TITLE
Wondering about port into the ffmpeg-5.x series

### ISSUE THREAD

**Issue by graysky2** [jc-kynesim/rpi-ffmpeg#48]
Hi John.  Do you have plans to port this fantastic patch set into the ffmpeg 5.x series?

**Comment by jc-kynesim** [comment]
In progress - but do NOT grab any branch that looks hopeful yet as it is currently non-working (probably doesn't even compile)

**Comment by graysky2** [comment]
Great to hear, just wondering.  Thanks!

**Comment by graysky2** [comment]
@jc-kynesim - I see Kodi just got 5.1.2 tagged for inclusion in Nexus.  Can you comment on the state of the port you've been working on?  Good for me to try it out?
