### ISSUE TITLE
drmWaitVBlank failed: Invalid argument

### ISSUE THREAD

**Issue by wasalm** [jc-kynesim/rpi-ffmpeg#6]
FFmpeg goves the warning:

drmWaitVBlank failed: Invalid argument.

**Comment by jc-kynesim** [comment]
Yes it does, but that means you are using vout_drm which is only a debug device and outline for how to write a better version of itself, so you should treat that module as "it does what it does". Having said that, as far as I can tell given the wonderful state of drm documentation, I think I'm calling it correctly - it is just broken.
