### ISSUE TITLE
black output matroska

### ISSUE THREAD

**Issue by spookyfirehorse** [jc-kynesim/rpi-ffmpeg#77]
matroska output gives

mpv out 

Error while decoding frame!
[ffmpeg/video] h264: non-existing PPS 0 referenced
[ffmpeg/video] h264: decode_slice_header error
[ffmpeg/video] h264: no frame!

**Comment by spookyfirehorse** [comment]
same like before in rtsp

thanks

**Comment by jc-kynesim** [comment]
Indeed - seems bust - I'll look at it (I thought I'd fixed this previously)

**Comment by spookyfirehorse** [comment]
great job man thanks !!!

**Comment by spookyfirehorse** [comment]
120 fps for dvdrendering is amazing

**Comment by spookyfirehorse** [comment]
mkv is running 

and 

dev/6.0/rpi_import_1 is running on latest ubuntu

greetings from vienna
