### ISSUE TITLE
ffmpeg 7.0 port in the works?

### ISSUE THREAD

**Issue by graysky2** [jc-kynesim/rpi-ffmpeg#90]
Hi John - wondering if you have any start on a port into ffmpeg-7.0?  Kodi is planning to merge [PR#24972](https://github.com/xbmc/xbmc/pull/24972) switching over to version 7.0 for v22 at some point.  Thanks!

**Comment by jc-kynesim** [comment]
Pretty sure you'll have spotted my port by now
